project:
  type: website

website:
  title: "GDSL-KRIHS-Exchange"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: UK-Workshop.qmd
        text: UK Workshop
      - href: International-Conference.qmd
        text: International Conference

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

